[package]
name = "synth-core"
version = "0.2.1"
authors = [
  "Damien Broka <damien@getsynth.com>",
  "Christos Hadjiaslanis <christos@getsynth.com>"
]
edition = "2018"

[features]
default = [ "python" ]
python = [ "pyo3" ]

[dev-dependencies]
tempfile = "3.1.0"

[dependencies]
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"

lazy_static = "1.4.0"

colored = "2.0.0"
anyhow = "1.0.32"

log = "0.4.11"
env_logger = "0.7.1"

async-std = { version = "1.6.4", features = [ "attributes", "unstable" ] }
tide = "0.13.0"

num_cpus = "1.0"
sysinfo = "0.15.2"
strsim = "0.10.0"

pyo3 = { version = "0.12.1", optional = true }

regex = "1.3.9"

fake = "2.2.3"
rand = "0.7.3"

chrono = "0.4.18"

rayon = "1.4.1"

bincode = "1.3.1"

num = "0.3.1"
rand_regex = "0.14.2"

synth-gen = { path = "../gen", features = [ "faker", "shared" ] }
